### ISSUE TITLE
"No module named 'past'"

### ISSUE THREAD

**Issue by chunyunma** [Xunius/markdown2zim#6]
Thank you for writing this script!  I recently downloaded it and tried the zimtomarkdown.py. However, I kept getting this error message:

> Traceback (most recent call last):
  File "zim2markdown.py", line 56, in <module>
    from past.builtins import basestring
ModuleNotFoundError: No module named 'past'

I looked up this error message online but did not find a satisfying solution. I also tried to comment out line #56 `from past.builtins import basestring`. The script would still run, but all the zim-styled links would be dropped in the converted markdown file.

I use python3 on a mac os.  Any guidance would be greatly appreciated!

**Comment by Xunius** [comment]
Hi,
It seems that other people solved this missing "past" module by installing "future":
```
pip install future
```
I guess that's related the python3 and python2 version compatibility issues, I made this using py2, and have not looked at it for quite some time.

**Comment by xiaobitou** [comment]
Thank you very much for the prompt reply!  I installed `future` and the script did run!  However, the inline links are still dropped in the markdown output file.  For example,
`[[www.this-is-a-url.com|text]]` ->  `[text](None)`

**Comment by Xunius** [comment]
I can confirm that bug. I made some dirty quick fix now this `[[www.this-is-a-url.com|text]]` type of link should work. You could get a new copy of the code and try it out.

But zim links are probably still buggy, I was trying to convert the note hierarchy of zim into file paths, like `[[:level1_note]]` -> `/home/user_name/zimnotes/level1_note.txt`. But for complex structures it won't work. If you encounter such issues please contract again and I'll see what I can do.

**Comment by xiaobitou** [comment]
Thank you so much!!  It has so far worked for me. :)

**Comment by techgique** [comment]
I can also confirm that `pip install future` fixed the error. I have zim installed on Fedora 32.
